spring.application.name=u3tournaments

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=C##U3_APP
spring.datasource.password=gugu
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.issuer=u3-tournaments-api
jwt.expiration-seconds=3600